source 'https://rubygems.org'

gem 'rails', '~> 4.0.4'
gem 'puma'

gem 'pg'

gem 'sass-rails', '~> 4.0.2'
gem 'coffee-rails', '~> 4.0.0'

gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

gem 'rotp_rails', github: 'steakknife/rotp_rails'

group :doc do
  gem 'sdoc', require: false
end

group :development do
  gem 'pry-rails' # https://github.com/rweng/pry-rails
  gem 'pry'       # https://github.com/pry/pry
  gem 'pry-awesome_print' # https://github.com/steakknife/pry-awesome_print
  gem 'pry-debugger' # https://github.com/nixme/pry-debugger
  gem 'debugger'  # https://github.com/cldwalker/debugger
  gem 'pry-rescue' # https://github.com/ConradIrwin/pry-rescue
  gem 'pry-stack_explorer' # https://github.com/pry/pry-stack_explorer

  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets', '~> 1.0.2'
end
